-- Migration: 20251214_init
-- Description: Initial setup for users and words tables.

-- Users table: Stores telegram user info and language preferences
create table if not exists users (
  id bigint generated by default as identity primary key,
  telegram_id bigint unique not null,
  native_lang text not null,
  target_lang text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Words table: Stores the vocabulary for each user
create table if not exists words (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id) on delete cascade,
  original text not null,
  translation text not null,
  context_sentence text,
  status text default 'new', -- 'new', 'learning', 'learned'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) is good practice
-- Note: You might need to adjust policies depending on your specific postgres provider setup if using RLS.
alter table users enable row level security;
alter table words enable row level security;
