-- Migration: 20251215_init
-- Description: Consolidated initialization for Users, Words, Progress, State, and Views.
--              Includes visual learning support (context split).

-- 1. Users Table
create table if not exists users (
  id bigint generated by default as identity primary key,
  telegram_id bigint unique not null,
  native_lang text not null,
  target_lang text not null,
  active_srs_mode text default 'sm2', -- 'sm2', 'pimsleur', 'fsrs', etc.
  active_failure_mode text default 'reset', -- 'reset' (default) or 'regress'.
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table users enable row level security;

-- 2. Words Table covering Phase 2 (Visual Learning)
create table if not exists words (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id) on delete cascade,
  original text not null,
  translation text not null,
  context_target text, -- Renamed from context_sentence
  context_native text, -- New for Visual Learning
  status text default 'new', -- 'new', 'learning', 'learned'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table words enable row level security;

-- Unique index to prevent duplicates (case-insensitive) per user
-- Unique index to prevent exact duplicates (original + context) per user
create unique index if not exists idx_words_user_original_context on words (user_id, lower(original), lower(context_target));

-- 3. User Progress Table (SRS)
create table if not exists user_progress (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id) on delete cascade not null,
  
  -- Exclusive Arcs (True Foreign Keys)
  word_id bigint references words(id) on delete cascade,
  phrase_id bigint, -- Future references phrases(id)
  dialog_id bigint, -- Future references dialogs(id)
  
  -- SRS Data
  next_review_at timestamp with time zone default now() not null,
  interval integer default 0, -- minutes
  confidence integer default 0, -- 0-100

  streak integer default 0,

  -- Multi-Algo State Storage
  srs_states jsonb default '{}'::jsonb, -- Stores state for ALL modes: {"sm2": {...}, "pimsleur": {...}}

  -- Direction Tracking (New for Bi-Directional SRS)
  direction text default 'target->native', -- 'target->native' or 'native->target'
  
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  
  -- Ensure exactly one unit type is associated
  constraint chk_one_unit_type check (num_nonnulls(word_id, phrase_id, dialog_id) = 1),
  
  -- Unique constraint per direction
  unique(user_id, word_id, direction),
  unique(user_id, phrase_id, direction),
  unique(user_id, dialog_id, direction)
);
create index idx_user_progress_scheduler on user_progress(user_id, next_review_at);

-- 4. User Bot State (Persistence & Locks)
create table if not exists user_bot_state (
  user_id bigint primary key references users(id) on delete cascade,
  is_busy boolean default false,
  options jsonb, -- Stores current task options
  updated_at timestamp with time zone default now() not null,
  last_message_id integer,
  last_message_chat_id bigint
);
alter table user_bot_state enable row level security;

-- 5. View for Efficient Scheduler Queries
create or replace view view_due_words as
select 
    up.id as progress_id,
    up.user_id,
    up.word_id as unit_id,
    'word' as unit_type, -- Hardcoded for this view
    up.next_review_at,
    up.interval,
    up.confidence,
    up.streak,
    up.direction,
    w.original as word_original,
    w.translation as word_translation,
    w.context_target as word_context_target,
    w.context_native as word_context_native,
    u.telegram_id as user_telegram_id
from user_progress up
join words w on up.word_id = w.id
join users u on up.user_id = u.id
where up.next_review_at <= now();
-- Migration: 20251216_switch_mode_rpc
-- Description: RPC function to efficiently switch SRS modes for a user.

create or replace function switch_user_srs_mode(p_user_id bigint, p_new_mode text)
returns void
language plpgsql
security definer
as $$
begin
  -- Update all user_progress rows for this user
  update user_progress
  set 
    -- 1. Update Flat Columns from JSONB (or defaults if missing)
    -- srs_states is { "mode": { "interval": ... } }
    
    interval = coalesce((srs_states->p_new_mode->>'interval')::int, 0),
    confidence = coalesce((srs_states->p_new_mode->>'confidence')::int, 0),
    streak = coalesce((srs_states->p_new_mode->>'streak')::int, 0),
    
    -- Check if next_review_at exists in state. If so, use it. Else, default to Now.
    next_review_at = case 
        when srs_states->p_new_mode->>'next_review_at' is not null 
        then (srs_states->p_new_mode->>'next_review_at')::timestamptz
        else now()
    end,

    -- Update metadata
    updated_at = now()
    
  where user_id = p_user_id;
end;
$$;
