-- Migration: 20251214_user_progress
-- Description: Create user_progress table for SRS tracking.

create table if not exists user_progress (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id) on delete cascade not null,
  
  -- Polymorphic reference logical link (word_id for now, future phrase/dialog id)
  unit_id bigint not null, 
  unit_type text not null check (unit_type in ('word', 'phrase', 'dialog')),
  
  -- SRS Data
  next_review_at timestamp with time zone default now() not null,
  interval integer default 0, -- interval in minutes
  confidence integer default 0, -- score 0-100
  streak integer default 0, -- number of consecutive correct answers
  
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  
  -- Ensure one progress record per unit per user
  unique(user_id, unit_id, unit_type)
);

-- Index for finding due reviews efficiently
create index idx_user_progress_scheduler on user_progress(user_id, next_review_at);

-- Backfill existing words into user_progress
-- We assume all existing items in 'words' are 'word' type and start fresh
insert into user_progress (user_id, unit_id, unit_type, next_review_at)
select user_id, id, 'word', now()
from words
on conflict (user_id, unit_id, unit_type) do nothing;
